/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busivytp1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

//Etape 1 : affichage 
//Etape 2 : normalisation
//Etape 3 : enregistrement (dans un fichier texte)
//Etape 4 : reconnaissance
/**
 *
 * @author mundial
 */
public class Dessin extends javax.swing.JComponent {

    Stroke stroke;
    Boolean finished;

    public Dessin() {
        super();
        setStroke(new Stroke());
        finished = false;
    }

    public  void setStroke(Stroke s){
        this.stroke = s;
    }
    
    public Stroke getStroke() throws CloneNotSupportedException {
        return stroke.clone();
    }
    

    public Boolean getFinished() {
        return finished;
    }

    public void setFinished(Boolean b) {
        finished = b;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        for (int i = 0; i < stroke.size(); i++) {
            // on saisit la couleur en fonction de la position du point
            if (i == 0) {
                g.setColor(Color.GREEN);
            } else if (i == (stroke.size() - 1)) {
                g.setColor(Color.RED);
            } else {
                g.setColor(Color.GRAY);
            }
            g2.fillOval((int) stroke.getPoint(i).getX(), (int) stroke.getPoint(i).getY(), 3, 3);
        }

        // on vérifie s il y a release avant de normaliser 
        if (finished) {
            for (int i = 0; i < stroke.size(); i++) {
                // on saisit la couleur en fonction de la position du point
                if (i == 0) {
                    g.setColor(Color.GREEN);
                } else if (i == (stroke.size() - 1)) {
                    g.setColor(Color.RED);
                } else {
                    g.setColor(Color.BLUE);
                }
                stroke.normalize();
                //g2.fillOval((int) stroke.getPoint(i).getX(), (int) stroke.getPoint(i).getY(), 3, 3);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
